print("--- loading silentGem.zs ---");

#Remove&Hide
mods.jei.JEI.removeAndHide(<silentgems:glowrose:0>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:1>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:2>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:3>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:4>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:5>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:6>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:7>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:8>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:9>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:10>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:11>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:12>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:13>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:14>);
mods.jei.JEI.removeAndHide(<silentgems:glowrose:15>);
mods.jei.JEI.removeAndHide(<silentgems:chaosflowerpot>);
mods.jei.JEI.removeAndHide(<silentgems:quivernonempty>);
mods.jei.JEI.removeAndHide(<silentgems:quiver>);
mods.jei.JEI.removeAndHide(<silentgems:chaosnode>);
mods.jei.JEI.removeAndHide(<silentgems:phantomlight>);
mods.jei.JEI.removeAndHide(<silentgems:craftingmaterial:9>);
mods.jei.JEI.removeAndHide(<silentgems:craftingmaterial:12>);
mods.jei.JEI.removeAndHide(<silentgems:craftingmaterial:24>);
mods.jei.JEI.removeAndHide(<silentgems:craftingmaterial:25>);
mods.jei.JEI.removeAndHide(<silentgems:craftingmaterial:26>);
mods.jei.JEI.removeAndHide(<silentgems:craftingmaterial:34>);
mods.jei.JEI.removeAndHide(<silentgems:urn_upgrade_storage_basic>);
mods.jei.JEI.removeAndHide(<silentgems:urn_upgrade_storage_advanced>);
mods.jei.JEI.removeAndHide(<silentgems:urn_upgrade_vacuum>);
mods.jei.JEI.removeAndHide(<silentgems:materialgrader>);
mods.jei.JEI.removeAndHide(<silentgems:toolsoul>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:0>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:1>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:2>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:3>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:4>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:5>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:6>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:7>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:8>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:9>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:10>);
mods.jei.JEI.removeAndHide(<silentgems:armorframe:11>);
mods.jei.JEI.removeAndHide(<silentgems:dye:0>);
mods.jei.JEI.removeAndHide(<silentgems:dye:4>);
mods.jei.JEI.removeAndHide(<silentgems:food:6>);
mods.jei.JEI.removeAndHide(<silentgems:tipupgrade:0>);
mods.jei.JEI.removeAndHide(<silentgems:tipupgrade:1>);
mods.jei.JEI.removeAndHide(<silentgems:tipupgrade:2>);
mods.jei.JEI.removeAndHide(<silentgems:tipupgrade:3>);

<ore:rodSilver>.remove(<silentgems:craftingmaterial:9>);
mods.immersiveengineering.MetalPress.removeRecipe(<silentgems:craftingmaterial:9>);

#Remove Skill Orb
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "durability_boost"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "harvest_speed_boost"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "melee_damage_boost"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "magic_damage_boost"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "protection_boost"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "warm"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "chill"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "tag"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "head_bonus"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "crop_growth"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "mending"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "aquatic"}));
mods.jei.JEI.removeAndHide(<silentgems:skillorb:0>.withTag({SG_Skill_ID: "aerial"}));

#Remove Enchantment Token
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "endercore:autosmelt"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "extrautils2:xu.bladerang"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "extrautils2:xu.boomereaperang"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "extrautils2:xu.burnerang"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "extrautils2:xu.kaboomerang"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "abyssalcraft:multi_rend"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "abyssalcraft:sapping"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "enderio:soulbound"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "endercore:xpboost"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "extrautils2:xu.zoomerang"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:efficiency"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "oeintegration:oreexcavation"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:fortune"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "silentgems:gravity"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "cofhcore:insight"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "astralsorcery:enchantment.as.smelting"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "exnihilocreatio:sieve_efficiency"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "exnihilocreatio:sieve_fortune"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "exnihilocreatio:sieve_luck_of_the_sea"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:silk_touch"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "cofhcore:smashing"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "cofhcore:smelting"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:bane_of_arthropods"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "silentgems:magicdamage"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "abyssalcraft:coralium"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "enderio:witherweapon"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "abyssalcraft:dread"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:fire_aspect"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "woot:headhunter"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "silentgems:iceaspect"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:knockback"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "cofhcore:leech"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "silentgems:lifesteal"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "abyssalcraft:light_pierce"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "silentgems:lightningaspect"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:looting"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "draconicevolution:enchant_reaper"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:sharpness"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:smite"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:sweeping"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "cofhcore:vorpal"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:luck_of_the_sea"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:lure"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:flame"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:infinity"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "cofhcore:multishot"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:power"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:punch"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "enderio:witherarrow"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "advancedrocketry:spacebreathing"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:aqua_affinity"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:blast_protection"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:depth_strider"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:feather_falling"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:fire_protection"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:frost_walker"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "abyssalcraft:iron_wall"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "openblocks:last_stand"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "astralsorcery:enchantment.as.nightvision"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:projectile_protection"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:protection"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "bibliocraft:bibliocraft.readingench"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "enderio:repellent"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:respiration"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:thorns"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "openblocks:explosive"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:binding_curse"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "projectred-expansion:electric_efficiency"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "bibliocraft:bibliocraft.deathcompassench"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "openblocks:flim_flam"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "cofhcore:holding"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:mending"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "cofhcore:soulbound"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "silentgems:supercharged"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:unbreaking"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "minecraft:vanishing_curse"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:0>.withTag({TokenEnchantments: [{lvl: 1 as short, id: "enderio:shimmer"}]}));
mods.jei.JEI.removeAndHide(<silentgems:enchantmenttoken:256>);
recipes.removeByRecipeName("silentgems:enchantment_token_clear");
recipes.removeByRecipeName("silentgems:enchantment_token_enchantment.xpboost");
recipes.removeByRecipeName("silentgems:enchantment_token_enchantment.autosmelt");
recipes.removeByRecipeName("silentgems:enchantment_token_enchantment.soulbound");

#Remove All Arrow
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Flint Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 4342338, Damage: 1.5 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Ruby Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 15080733, Damage: 6.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Garnet Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 15093533, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Topaz Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 15102237, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Amber Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 15115037, Damage: 2.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Heliodor Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 15123741, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Peridot Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10741277, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Green Sapphire Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 1959453, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Indicolite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 1959554, Damage: 2.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Aquamarine Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 1959654, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Sapphire Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 1908198, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Iolite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 6299110, Damage: 2.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Amethyst Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10690022, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Agate Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 15080934, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Morganite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 16746750, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Onyx Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 3092271, Damage: 7.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Opal Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 15000804, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Carnelian Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10685952, Damage: 2.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Spinel Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10699776, Damage: 5.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Citrine Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10706688, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Jasper Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10717184, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Golden Beryl Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10724096, Damage: 2.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Moldavite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 8954624, Damage: 5.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Malachite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 41782, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Turquoise Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 41864, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Moonstone Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 28067, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Blue Topaz Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 7075, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Tanzanite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 6226083, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Violet Sapphire Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 9765027, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Lepidolite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10682490, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Ametrine Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10682450, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Black Diamond Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 1973790, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Alexandrite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 9013641, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Pyrope Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 16729460, Damage: 6.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Coral Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 16733509, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Sunstone Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 16741445, Damage: 5.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Cat's Eye Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 16761157, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Zircon Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 16777029, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Jade Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 10682181, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Chrysoprase Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 6618949, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Apatite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 4587473, Damage: 2.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Fluorite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 4575743, Damage: 2.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Kyanite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 4555775, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Sodalite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 5522943, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Ammolite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 14697983, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Kunzite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 16729568, Damage: 5.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Rose Quartz Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 16742582, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Tektite Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 9403499, Damage: 4.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Pearl Arrow"}, SGArrowStats: {ColorShaft: 9004839, ColorFletching: 16777215, ColorHead: 14870769, Damage: 3.0 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Ruby Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 15080733, Damage: 10.349999 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Garnet Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 15093533, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Topaz Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 15102237, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Amber Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 15115037, Damage: 5.75 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Heliodor Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 15123741, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Peridot Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10741277, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Green Sapphire Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 1959453, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Indicolite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 1959554, Damage: 5.75 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Aquamarine Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 1959654, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Sapphire Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 1908198, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Iolite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 6299110, Damage: 5.75 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Amethyst Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10690022, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Agate Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 15080934, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Morganite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 16746750, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Onyx Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 3092271, Damage: 11.5 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Opal Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 15000804, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Carnelian Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10685952, Damage: 5.75 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Spinel Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10699776, Damage: 9.2 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Citrine Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10706688, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Jasper Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10717184, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Golden Beryl Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10724096, Damage: 5.75 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Moldavite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 8954624, Damage: 9.2 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Malachite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 41782, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Turquoise Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 41864, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Moonstone Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 28067, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Blue Topaz Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 7075, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Tanzanite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 6226083, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Violet Sapphire Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 9765027, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Lepidolite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10682490, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Ametrine Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10682450, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Black Diamond Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 1973790, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Alexandrite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 9013641, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Pyrope Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 16729460, Damage: 10.349999 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Coral Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 16733509, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Sunstone Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 16741445, Damage: 9.2 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Cat's Eye Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 16761157, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Zircon Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 16777029, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Jade Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 10682181, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Chrysoprase Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 6618949, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Apatite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 4587473, Damage: 5.75 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Fluorite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 4575743, Damage: 5.75 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Kyanite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 4555775, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Sodalite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 5522943, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Ammolite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 14697983, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Kunzite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 16729568, Damage: 9.2 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Rose Quartz Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 16742582, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Tektite Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 9403499, Damage: 8.05 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:arrow:0>.withTag({SGConstruction: {}, display: {Name: "Supercharged Pearl Arrow"}, SGArrowStats: {ColorShaft: 13151753, ColorFletching: 16777215, ColorHead: 14870769, Damage: 6.8999996 as float}}));
mods.jei.JEI.removeAndHide(<silentgems:craftingmaterial:33>);
mods.jei.JEI.removeAndHide(<silentgems:stonetorch>);

print("--- silentGem.zs initialized ---");